site_name: 'Выбор сервера для коробочной версии Битрикс24'

site_author: 'makks'

docs_dir: 'docs'

theme:
  name: 'material'

nav:
  - Home: 'index.md'
  - 'Тарифы':
      - 'Тест': './rates/index.md'
